//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public CAR()
        {
            this.RENTALs = new HashSet<RENTAL>();
        }
    
        public string CAR_NO { get; set; }
        public Nullable<int> CAR_MAKE { get; set; }
        public Nullable<int> BODY_TYPE { get; set; }
        public string MODEL { get; set; }
        public Nullable<int> KM_TRAVELLED { get; set; }
        public Nullable<int> KM_SERVICE { get; set; }
        public string AVAILABLE { get; set; }
    
        public virtual CAR_MAKE CAR_MAKE1 { get; set; }
        public virtual CAR_BODY_TYPE CAR_BODY_TYPE { get; set; }
        public virtual ICollection<RENTAL> RENTALs { get; set; }
    }
}
