//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_BODY_TYPE
    {
        public CAR_BODY_TYPE()
        {
            this.CARs = new HashSet<CAR>();
        }
    
        public int BODY_TYPE_ID { get; set; }
        public string BODY_TYPE { get; set; }
    
        public virtual ICollection<CAR> CARs { get; set; }
    }
}
