//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CLDV_10082168Entities : DbContext
    {
        public DB_CLDV_10082168Entities()
            : base("name=DB_CLDV_10082168Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAR> CARs { get; set; }
        public DbSet<CAR_BODY_TYPE> CAR_BODY_TYPE { get; set; }
        public DbSet<CAR_MAKE> CAR_MAKE { get; set; }
        public DbSet<DRIVER> DRIVERs { get; set; }
        public DbSet<INSPECTOR> INSPECTORs { get; set; }
        public DbSet<RENTAL> RENTALs { get; set; }
        public DbSet<RETURN> RETURNs { get; set; }
    }
}
