<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Cars.aspx.cs" Inherits="CarRentalManager.Cars" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <h1>Vehicle Details</h1>
    </div>

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/AddCar" Text="Add New Car" runat="server" />
    <asp:GridView runat="server" ID="carsGrid"
        ItemType="CarRentalManager.Models.CAR" DataKeyNames="CAR_NO" 
        SelectMethod="carsGrid_GetData"
        UpdateMethod="carsGrid_UpdateItem" DeleteMethod="carsGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="true">
    </asp:GridView>

    <asp:GridView runat="server" ID="carmakeGrid"
        ItemType="CarRentalManager.Models.CAR_MAKE" DataKeyNames="CAR_MAKE_ID" 
        SelectMethod="carmakeGrid_GetData"
        AutoGenerateColumns="true">
    </asp:GridView>

    <asp:GridView runat="server" ID="bodytypeGrid"
        ItemType="CarRentalManager.Models.CAR_BODY_TYPE" DataKeyNames="BODY_TYPE_ID" 
        SelectMethod="bodytypeGrid_GetData"
        AutoGenerateColumns="true">
    </asp:GridView>
</asp:Content>
