<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Drivers.aspx.cs" Inherits="CarRentalManager.Drivers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <h1>Driver Details</h1>
    </div>

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/AddDriver" Text="Add New Driver" runat="server" />
    <asp:GridView runat="server" ID="driversGrid"
        ItemType="CarRentalManager.Models.DRIVER" DataKeyNames="DRIVER_NO" 
        SelectMethod="driversGrid_GetData"
        UpdateMethod="driversGrid_UpdateItem" DeleteMethod="driversGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="true">
    </asp:GridView>
</asp:Content>
