<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Inspectors.aspx.cs" Inherits="CarRentalManager.Inspectors" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <h1>Inspector Details</h1>
    </div>

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/AddInspector" Text="Add New Inspector" runat="server" />
    <asp:GridView runat="server" ID="inspectorsGrid"
        ItemType="CarRentalManager.Models.INSPECTOR" DataKeyNames="INSPECTOR_NO" 
        SelectMethod="inspectorsGrid_GetData"
        UpdateMethod="inspectorsGrid_UpdateItem" DeleteMethod="inspectorsGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
        AutoGenerateColumns="true">
    </asp:GridView>
</asp:Content>
