<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Rentals.aspx.cs" Inherits="CarRentalManager.Rentals" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <h1>Rent/Return Details</h1>
    </div>

    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <asp:HyperLink NavigateUrl="~/AddRental" Text="Add New Rental" runat="server" />
    <asp:GridView runat="server" ID="rentalsGrid"
        ItemType="CarRentalManager.Models.RENTAL" DataKeyNames="RENTAL_NO" 
        SelectMethod="rentalsGrid_GetData"
        AutoGenerateColumns="true">
    </asp:GridView>

    <asp:HyperLink NavigateUrl="~/AddReturn" Text="Add New Return" runat="server" />
    <asp:GridView runat="server" ID="returnsGrid"
        ItemType="CarRentalManager.Models.RETURN" DataKeyNames="RENTAL_NO" 
        SelectMethod="returnsGrid_GetData"
        DeleteMethod="returnsGrid_DeleteItem"
        AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="RENTAL_NO" />
            <asp:DynamicField DataField="RETURNED_DATE" />
            <asp:DynamicField DataField="ELAPSED_TIME" />
            <asp:DynamicField DataField="FINE" />
        </Columns>
    </asp:GridView>
</asp:Content>
